[target.thumbv7em-none-eabi]
runner = "probe-run --chip STM32H743ZITx"
rustflags = [
  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabi"   # Cortex-M4 and Cortex-M7 (no FPU)

[alias]
rb = "run --bin"
rrb = "run --release --bin"
re = "run --example"
rre = "run --release --example"